<style>
   th {
        color: red;
        text-align: left;
    }
</style>
<h1>List of Users</h1>
<p><a href="<?php echo $this->url(array('action' => 'add')); ?>">Add New User</a></p>
<table border="1">
    <thead>
        <tr>
            <th>ID <?=$this->message ?></th>
            <th>Nom</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <td><?php echo $this->escape($user->id); ?></td>
                <td><?php echo $this->escape($user->nom); ?></td>
                <td><?php echo $this->escape($user->email); ?></td>
                <td>
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $user->id)); ?>">Edit</a> |
                    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $user->id)); ?>" onclick="return confirm('Are you sure?');">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div id="app">
    {{message}}
</div>
<script>
  const { createApp, ref } = Vue

  createApp({
    setup() {
      const message = ref('Hello vue!')
      return {
        message
      }
    }
  }).mount('#app')
</script>
